name: Cake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          branch: reactor
          name: BepInEx-reactor
          repo: NuclearPowered/BepInEx

      - name: Cake Action
        run: sh build.sh
        env:
          STEAM: ${{ secrets.STEAM }}

      - uses: actions/upload-artifact@v2
        with:
          name: Reactor.dll
          path: Reactor/bin/Release/netstandard2.1/reobfuscated/Reactor.dll

      - uses: actions/upload-artifact@v2
        with:
          name: Reactor.Debugger.dll
          path: Reactor.Debugger/bin/Release/netstandard2/reobfuscated/Reactor.Debugger.dll
